app = 'wanderwise-at'
primary_region = 'ord'

[env]
TZ = "America/Chicago"

[build]

[[services]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.static]]
    guest_path = "/images"      # Path to the images in your app’s root
    url_prefix = "/images"      # URL prefix for accessing the images directory

  routes = [
    {src = "/.*", dest = "/index.html"}
  ]

[[vm]]
  size = 'shared-cpu-1x'